sudo: required
language: go
go_import_path: github.com/ricastell/hdfs
go: 1.13
env:
- PLATFORM=cdh5
- PLATFORM=cdh5 KERBEROS=true
- PLATFORM=hdp2
before_install:
- export GO111MODULE=on # Travis installs into $GOPATH/src, which disables module support by default.
install:
- git clone https://github.com/sstephenson/bats $HOME/bats
- mkdir -p $HOME/bats/build
- "$HOME/bats/install.sh $HOME/bats/build"
- export PATH="$PATH:$HOME/bats/build/bin"
- ./travis-setup.sh $PLATFORM
before_script:
- export HADOOP_CONF_DIR="/etc/hadoop/conf"
- find internal/protocol -name *.pb.go | xargs touch # so make doesn't try to regen protobuf files
script: make test
before_deploy: make release
cache:
- "$HOME/bats"
